### ISSUE TITLE
Blender 4.0 support

### ISSUE THREAD

**Issue by ahosama** [artempoletsky/blender_slap_it#3]
Getting this error in 4.0:
Error: Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\slap_it.py", line 103, in execute
    bpy.ops.mesh.knife_project(override);
  File "C:\Program Files\Graphics\blender-windows64\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Graphics\blender-windows64\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported

Any plans to update the addon for the api changes with context override?

**Comment by ArieLeo** [comment]
2nd this, any plan to support blender 4+?

**Comment by QuaziK** [comment]
Made a pull request for updates to 4.4

**Comment by artempoletsky** [comment]
PR merged
